apiVersion: v1
kind: Secret
metadata:
  name: activity-secrets
  namespace: default
type: Opaque
data:
  DB_USER: bXl1c2Vy   # base64 encoded
  DB_PASS: cGFzc3dvcmQ=  # base64 encoded
stringData:
  KAFKA_TOPIC: "user-activity"
  KAFKA_BROKERS: "kafka:9092"
  MONGO_URI: "mongodb://mongo:27017/activitydb"
  NODE_ENV: "production"
